// REDUX ACTION TYPES
export const AGENTS_REQUEST = 'AGENTS_REQUEST'
export const AGENTS_ERROR = 'AGENTS_ERROR'
export const AGENTS_SUCCESS = 'AGENTS_SUCCESS'
export const AGENT_BY_ID_REQUEST = 'AGENT_BY_ID_REQUEST'
export const AGENT_BY_ID_ERROR = 'AGENT_BY_ID_ERROR'
export const AGENT_BY_ID_SUCCESS = 'AGENT_BY_ID_SUCCESS'
