// REDUX ACTION TYPES
export const RULES_REQUEST = 'RULES_REQUEST'
export const RULES_ERROR = 'RULES_ERROR'
export const RULES_SUCCESS = 'RULES_SUCCESS'
export const RULE_BY_ID_REQUEST = 'RULE_BY_ID_REQUEST'
export const RULE_BY_ID_ERROR = 'RULE_BY_ID_ERROR'
export const RULE_BY_ID_SUCCESS = 'RULE_BY_ID_SUCCESS'
